# The Gateway API endpoint
apiUrl: ${cf:${self:custom.settings.infrastructureStackName}.WebsiteUrl}

# The stack name of the 'backend' serverless service
backendStackName: ${self:custom.settings.namespace}-backend

# The stack name of the 'cloudfront' serverless service
infrastructureStackName: ${self:custom.settings.namespace}-infrastructure

# The S3 bucket name used to host the static website
websiteBucketName: ${cf:${self:custom.settings.infrastructureStackName}.WebsiteBucket}

# The id of the CloudFront distribution for the static website
websiteCloudFrontId: ${cf:${self:custom.settings.infrastructureStackName}.CloudFrontId}

# URL of the website
websiteUrl: ${cf:${self:custom.settings.infrastructureStackName}.WebsiteUrl}

# Branding
brandPageTitle: 'Service Workbench'
brandMainTitle: 'Service Workbench on AWS (${self:custom.settings.envName}/${self:custom.settings.awsRegion})'
brandLoginTitle: 'Service Workbench'
brandLoginSubtitle: 'Service Workbench on AWS (${self:custom.settings.envName}/${self:custom.settings.awsRegion})'

versionAndDate: 'Version ${self:custom.settings.versionNumber} (${self:custom.settings.versionDate})'

# After how many minutes should the auto logout dialog be displayed? once displayed the user has 1 minute to dismiss
# the dialog, otherwise they will be automatically logged out
autoLogoutTimeoutInMinutes: 30

# Registration page
userRegistrationTitle: "WELCOME TO SERVICE WORKBENCH"
userRegistrationSummary: "<p>Service Workbench provides a self-service, three-click, on-demand service for researchers to build research environments in minutes without needing cloud infrastructure knowledge. Fill out the form below to create your account on Service Workbench hosted on AWS.</p>"
userRegistrationTOS: "I am 18 years or older"
userRegistrationSuccess: "<p>Your Service Workbench account has been successfully created. What you should expect next:</p><ol><li>The Service Workbench administrator will review your account.</li><li>Once your account is activated, you can login to Service Workbench and start your research.</li></ol>"
userRegistrationLoginWarning: ""